### ISSUE TITLE
The package behind PackageSecurityHealthCheck is abandoned

### ISSUE THREAD

**Issue by srichter** [ans-group/laravel-health-check#63]
PackageSecurityHealthCheck uses `sensiolabs/security-checker` which has been abandoned since January and the underlying API no longer functions.

If we want to keep the check working, I can open a PR to have it use `enlightn/security-checker` instead. However, based on the fact that it was broken for nearly a year without anyone noticing, I'm not sure there's demand for it.

**Comment by Gman98ish** [comment]
@srichter ha good point. I'm a little hesitant to remove the check outright as that's a breaking change and could mess with some people's API's. 

Not sure what the best solution is here, we could mark it as deprecated, but I like the idea of switching to the package you've suggested.

**Comment by Gman98ish** [comment]
when I get a sec, I'll switch it over, but if you're up for it feel free to submit a PR

**Comment by phily245** [comment]
This is on the v2 dev branch now

**Comment by phily245** [comment]
v2.0.0 is now live, this has been resolved, thank you for the PR @srichter
